### ISSUE TITLE
Make print_to_gt work with nested groupings 

### ISSUE THREAD

**Issue by statasaurus** [GSK-Biostatistics/tlang#16]

**Comment by statasaurus** [comment]
- [ ] Remove grouping if not a spanning group header 
- [ ] Add in spanning label to row_grp_plan
- [ ]

**Comment by bzkrouse** [comment]
note that in gt you can either do spanning group header or label in its own column using tab_options(row_group.as_column = TRUE)  https://github.com/rstudio/gt/issues/577

**Comment by bzkrouse** [comment]
@statasaurus should row group label specifications become an element? A few opts to include:
- Spanning label above rows
- label on the side of rows (see comment above) 
- no spanning label 
- indentation # spaces
