### ISSUE TITLE
add scientific to frmt 

### ISSUE THREAD

**Issue by statasaurus** [GSK-Biostatistics/tlang#22]

**Comment by thebioengineer** [comment]
Per discussion - will look at the formats to be used to define scientific outputs

frmt("X.XXX", scientific = "x10^X')
frmt("X.XXX", scientific = "*10^X")
frmt("X.XXX", scientific = "e^X")

**Comment by karima662** [comment]
You can use the following as examples, it should work:
`data <- tibble(vals = c(0.01234, 0.80257, 0.30599, 0.73012, 1.1462, 0.21261, 0.91970))`
`apply_frmt.frmt(.data = data, values = sym("vals"), frmt_def = frmt(expression = "x.xx"))`
`apply_frmt.frmt(.data = data, values = sym("vals"), frmt_def = frmt(expression = "x.xxx"))`
`apply_frmt.frmt(.data = data, values = sym("vals"), frmt_def = frmt(expression = "x.xxx", scientific = "x10^x"))`
`apply_frmt.frmt(.data = data, values = sym("vals"), frmt_def = frmt(expression = "x.xxx", scientific = "*10^x"))`
`apply_frmt.frmt(.data = data, values = sym("vals"), frmt_def = frmt(expression = "x.xxx", scientific = " x10^x"))`
`apply_frmt.frmt(.data = data, values = sym("vals"), frmt_def = frmt(expression = "x.xxx", scientific = " *10^x"))`
