### ISSUE TITLE
Print function for frmt_when

### ISSUE THREAD

**Issue by statasaurus** [GSK-Biostatistics/tlang#60]

**Comment by karima662** [comment]
Test with the following:

combine <- frmt_combine(expression = "{Min}, {Max}",
                        Min = frmt("XX"),
                        Max = frmt("XXX"))

when <- frmt_when("==100"~ frmt(""),
                  "==0"~ "",
                  "TRUE" ~ frmt("(XXX.X%)"))

combine
when

**Comment by karima662** [comment]
I think this issue can be closed now
