### ISSUE TITLE
Issue with creating Table 14-1.01 in CDSIC pilot 

### ISSUE THREAD

**Issue by statasaurus** [GSK-Biostatistics/tlang#78]
The following code produces the following error: 
Error in local_error_context(dots = dots, .index = i, mask = mask) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
```{r}
data <- crossing(
  label = c("Intent-To-Treat (ITT)",
            "Safety",
            "Efficacy",
            "Complete Week 24",
            "Complete Study"
  ), 
  column = c("Placebo\n(N=XX)",	
             "Xanomeline\nLow Dose\n(N=XX)",
             "Xanomeline\nHigh Dose\n(N=XX)",
             "Total\n(N=XXX)" 
  ),
  param = c("n", "pect")
)

tfrmt(
  label = "label", 
  column = "column",
  param = "param",
  title = "Summary of Populations",
  body_style = table_body_plan(
    frmt_structure(
      group_val = ".default", label_val = ".default", 
      frmt_combine("n ({pect}%)",
                   n = frmt("xx"),
                   pect = frmt("xxx"))
    )
  )
) %>% 
  print_mock_gt(data)
```

**Comment by statasaurus** [comment]
Issue was the frmt_combine was written wrong. better error messages?

**Comment by thebioengineer** [comment]
should we have it check to see if a param is listed in the string and not escaped? also maybe return the expression that is failing?

**Comment by statasaurus** [comment]
The params are not the problem. It is the value field. And I was thinking it will just write over it if you pass a value field in so I don't think we need to do anything. The behaviour would be somewhat expected given you are using the print to mock function
