### ISSUE TITLE
Look at if we can add a summary line into a GT table without using the GT summary functions 

### ISSUE THREAD

**Issue by statasaurus** [GSK-Biostatistics/tlang#8]

**Comment by thebioengineer** [comment]
So it looks like the way that gt works is that you layer on the various changes to the data you plan on presenting, but it does not apply them until the very end when it goes to present it - at least it tries not to. There end up being slight changes to the `_data` entry in the gt_tbl object (addition of `::rownames::` for example).

Everything looks to be stored as a function in an element in a list that is the structure of the gt object. When the table gets printed is when it goes through and applies the changes step by step to an output dataset that also receives formatting. I appreciate rich's approach on that. however it does mean us hijacking things to do what you are thinking (a summary table entry) is both not simple and ends up with weird function situations

what we could do, stealing from his example on summary_rows is the following, which I don't think is a good idea:

```r

library(gt)
library(tidyverse)

exibble_a <-
  exibble %>%
  select(-c(fctr, date, time, datetime)) %>%
  gt(rowname_col = "row", groupname_col = "group") %>%
  fmt_missing(columns = everything())

num_mean_val <- function(x, ...){
  "These"
}

num_total_val <- function(x, ...){
  "are"
}

num_sd_val <- function(x, ...){
  "our values"
}

# Create groupwise summary rows for both
# groups (using `groups = TRUE`); use the
# `mean()`, `sum()`, and `sd()` functions
# (only for the `num` column)
exibble_b <- exibble_a %>% 
  summary_rows(
    groups = "grp_a",
    columns = num,
    fns = c(
      average = "num_mean_val",
      total = "num_total_val",
      SD = "num_sd_val"
    ),
    formatter = fmt_markdown
  )

```
